- Delete.java
- Driver.java
Created the delete class using what mathew has shown of the reader class so farn and updated the driver to implement these changes as well
> Refactored the delete method into the delete class

- Delete.java
- Driver.java
added new functionality to the customer order method and made the necessary changes to the driver class
to implement the changes
> Delete Customer order method

- Bot.java
- BotCommands.java
- Driver.java
- pom.xml
converted project in to a maven project
imported maven dependencies
> Create Classes for bot and bot commands

- CustOrder.java
- Driver.java
- Update.java
I added the methods for the update class. There is a method to update the product inventory, a method to update the customer inventory, and two methods to update the product inventory to reflect customer orders. I tested the first, second, and fourth methods. The third method is meant to be called from the method that creates customer orders, so I am just waiting to test it out once create class is finalized.
I also updated the driver class to reflect the changes to the update class.
custOrder class was also updated.
I also moved the updateProducts method from the create class into the update class.
> Added methods update class

- Create.java
I just changed the scanners, corrected a couple spelling errors in the comments, and changed the update products method so it calls the method from the update class.
> Made very minor changes to create class.

- Driver.java
- crudOperations/Create.java
- crudOperations/CrudOperator.java
- crudOperations/Delete.java
- crudOperations/Read.java
- crudOperations/Update.java
- src/main/java/botCode/Bot.java
- src/main/java/botCode/BotCommands.java
- src/main/java/main/Driver.java
- src/main/java/oldCode/Crud.java
- src/main/java/oldCode/CrudTest.java
- src/main/java/oldCode/CustOrder.java
- testing/DeleteTest.java
- testing/ReadTest.java
So this was a pull request from last sprint that I wanted to implement but ran out of time. 
All I did was put our classes into packages that way the classes are organized and got rid of the default package.  For some reason the bot, oldCode, and main packages are being placed in a source folder for some reason.  This maybe because of the maven project in eclipse.
> Created Packages for our classes

- crudOperations/DataTransfer.java
- testing/DataTransferTest.java
I created a DataTransfer class that uses getters and setters for all of the data in the inventory table.  This will allow us to temporarily store the data outside of the database.  This class can be used anywhere in our project by creating a new instance of the DataTransfer class and using the methods in the class.
I also created a unit test to test the DataTransfer class to make sure it's doing what its suppose to do.  The unit tests passed so it should be good to go.
> Data Transfer Object

- crudOperations/Read.java
- src/main/java/main/GUI.java
I added a JTable and a JScrollPane to the GUI that will display all of the data from the database. I had to change the layout of the GUI slightly to make this work. I also added three methods to the Read class. One reads every row of the database into an array that can be used for the JTable and the other two find the number of columns and rows in the database.
> Added JTable to the GUI and added methods to read class

- crudOperations/Create.java
- src/main/java/main/GUI.java
All of the buttons seem to work as intended and each has its own confirmation prompt you have to agree to before it goes through with the code
> Added functionality to create, update, and delete buttons in the GUI 

- src/main/java/main/Products.java
Recreated our current GUI into a JFrame to make switching between pages simpler
> Jframe products gui

- crudOperations/LoginManager.java
- src/main/java/main/LoginFrame.java
- src/main/java/main/MainMenuFrame.java
- src/main/java/main/SignUpFrame.java
So I added a lot of code to get this to work.  I created 3 new Jframes called LoginFrame, SignUpFrame, and MainMenuFrame.  I also created a new SQL data table called login in our database and created a new class called LoginManager to process the data from that table.  
- The login frame takes in a user name and password and checks them with an existing user name and password in the login data table.  If it matches you enter the main menu frame, if not then the GUI prompts you that the username or password is incorrect and clears the inputs. This frame also has a sign up button that opens the sign up frame.
- The sign up frame has you enter a new username and password and also confirms that you re-enter the password.  If you don't re-enter the password it will prompt you.  If everything …
> Login and Sign Up GUI Features

- crudOperations/Create.java
- crudOperations/Read.java
- src/main/java/main/FinanceFrame.java
- src/main/java/main/MainMenuFrame.java
I created the finance frame for the GUI. I added a button to the MainMenuFrame that opens the finance frame. I added a new method to the read class that passes all the data from the finance table into an array for use in the finance JTable. I also made a minor change to the read class.
> Added Finance Frame to GUI

- crudOperations/DataTransfer.java
- src/main/java/main/Products.java
I updated the data transfer class to hold data from the customer orders table.   I also added a back button to the inventory GUI to return the user back to the main menu frame.  
Everything worked on my end so it should be gooo.
> Updated Transfer Object and Added Feature to Inventory Frame

- crudOperations/DataTransfer.java
- crudOperations/Read.java
- src/main/java/main/MainMenuFrame.java
- src/main/java/main/OrderSearch.java
- src/main/java/main/Orders.java
- src/main/java/main/Products.java
Created the GUI page for the customer orders which displays all customer orders. Has a button to return to the main menu.
added a search button to the customer orders GUI which searches for all
orders made with a specific email and displays them
added a new method to the transfer object to set and get the date an
order was placed
added a new method in the read class to get the data for customer order
search
fixed some indenting
> Customer orders GUI 

- src/main/java/botCode/BotCommands.java
> Final update to bot commands

- src/main/java/main/FinanceFrame.java
- src/main/java/main/LoginFrame.java
- src/main/java/main/MainMenuFrame.java
- src/main/java/main/OrderSearch.java
- src/main/java/main/Orders.java
- src/main/java/main/Products.java
Redesigned the GUI to look nicer and not blind anyone
> GUI redesign

- crudOperations/Create.java
- src/main/java/email/CustomerEmail.java
- src/main/java/main/Orders.java
So I created a new package called email and created a new class called CustomerEmail.   I also created a dummy google account that sends the emails. The CustomerEmail class has one method that takes in an email address and sends an email using the dummy google account.  If the email address isn't a valid email address then method still runs and doesn't crash.
I also made changes to the createCustomerOrder method in the Create class to be able to send emails. 
I also added a new button to our customer order GUI to take input from the user and create a customer order.  
- **One thing to note is that if you want to run this code you need to add the  javax.mail.jar file to the java build path in our project**
Everything worked on my end so it should be good.
> Created an Email feature for Customer Orders

- src/main/java/email/CustomerEmail.java
Forgot to add documentation to the email class so I added some documentation and added a period to the email message.
Everything worked on my end so it should be good.
> Added Documentation to Email class

- crudOperations/Create.java
- crudOperations/Read.java
- crudOperations/Update.java
- src/main/java/main/Orders.java
Added two methods that update the finance table when new orders are placed and when an order is updated. Added another button to the orders frame to update a customer order. Made minor changes to create and read classes.
> Made the finance table dynamic and added button to Orders class

- src/main/java/botCode/Bot.java
- src/main/java/botCode/BotCommands.java
- src/main/java/botCode/BotOperations.java
- src/main/java/main/BotDriver.java
- src/main/java/main/Driver.java
Created separate Driver for bot, added a cancel order command, removed bot creation from main driver, made documentation for bot commands
> Final Bot Changes
